//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFacDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int ID_Factura { get; set; }
        public int Num_Factura { get; set; }
        public System.DateTime Fecha { get; set; }
        public int ID_Cliente { get; set; }
        public int ID_Producto { get; set; }
        public int Cantidad { get; set; }
        public int Subtotal { get; set; }
        public int Descuento { get; set; }
        public int Total { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
