<?xml version="1.0" encoding="utf-8"?><Database Name="Facturacion" Class="FacturasDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-5MIO3GF\DAVIDPC;Initial Catalog=Facturacion;Integrated Security=True" SettingsObjectName="WebFacDatos.Properties.Settings" SettingsPropertyName="FacturacionConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdRol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Roles_Usuarios" Member="Roles" ThisKey="IdRol" OtherKey="Id" Type="Roles" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Roles">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Roles_Usuarios" Member="Usuarios" ThisKey="Id" OtherKey="IdRol" Type="Usuarios" />
    </Type>
  </Table>
  <Table Name="dbo.Proveedores" Member="Proveedores">
    <Type Name="Proveedores">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(225) NOT NULL" CanBeNull="false" />
      <Association Name="Proveedores_Productos" Member="Productos" ThisKey="Id" OtherKey="IdProveedor" Type="Productos" />
    </Type>
  </Table>
  <Table Name="dbo.Productos" Member="Productos">
    <Type Name="Productos">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Producto" Type="System.String" DbType="NVarChar(225) NOT NULL" CanBeNull="false" />
      <Column Name="Costo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Utilidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Impuesto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Existencia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdProveedor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Productos_Articulos" Member="Articulos" ThisKey="Id" OtherKey="IdProducto" Type="Articulos" />
      <Association Name="Proveedores_Productos" Member="Proveedores" ThisKey="IdProveedor" OtherKey="Id" Type="Proveedores" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Facturas" Member="Facturas">
    <Type Name="Facturas">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Factura" Type="System.String" DbType="NVarChar(225) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IdCliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descuento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Facturas_Articulos" Member="Articulos" ThisKey="Id" OtherKey="IdFactura" Type="Articulos" />
      <Association Name="Clientes_Facturas" Member="Clientes" ThisKey="IdCliente" OtherKey="Id" Type="Clientes" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Clientes" Member="Clientes">
    <Type Name="Clientes">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cedula" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NombreCompleto" Type="System.String" DbType="NVarChar(225) NOT NULL" CanBeNull="false" />
      <Association Name="Clientes_Facturas" Member="Facturas" ThisKey="Id" OtherKey="IdCliente" Type="Facturas" />
    </Type>
  </Table>
  <Table Name="dbo.Articulos" Member="Articulos">
    <Type Name="Articulos">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdFactura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Facturas_Articulos" Member="Facturas" ThisKey="IdFactura" OtherKey="Id" Type="Facturas" IsForeignKey="true" />
      <Association Name="Productos_Articulos" Member="Productos" ThisKey="IdProducto" OtherKey="Id" Type="Productos" IsForeignKey="true" />
    </Type>
  </Table>
</Database>