//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFacDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public Productos()
        {
            this.Facturas = new HashSet<Facturas>();
        }
    
        public int ID_Producto { get; set; }
        public string Producto { get; set; }
        public int Costo { get; set; }
        public int Utilidad { get; set; }
        public int Impuesto { get; set; }
        public int Stock { get; set; }
        public int Precio_Venta { get; set; }
    
        public virtual ICollection<Facturas> Facturas { get; set; }
    }
}
