
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace slnDatos
{

using System;
    using System.Collections.Generic;
    
public partial class Factura
{

    public Factura()
    {

        this.LineaArticuloes = new HashSet<LineaArticulo>();

    }


    public int Id { get; set; }

    public string Numero { get; set; }

    public System.DateTime Fecha { get; set; }

    public int IdCliente { get; set; }

    public int IdFormaPago { get; set; }

    public int IdTipoMoneda { get; set; }

    public decimal Total { get; set; }



    public virtual Cliente Cliente { get; set; }

    public virtual FormaPago FormaPago { get; set; }

    public virtual TipoMoneda TipoMoneda { get; set; }

    public virtual ICollection<LineaArticulo> LineaArticuloes { get; set; }

}

}
