//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.Articulos = new HashSet<Articulo>();
        }
    
        public int Id { get; set; }
        public string Factura1 { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdCliente { get; set; }
        public Nullable<int> Descuento { get; set; }
    
        public virtual ICollection<Articulo> Articulos { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
