//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.LineaArticuloes = new HashSet<LineaArticulo>();
        }
    
        public int Id { get; set; }
        public string Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdCliente { get; set; }
        public int IdFormaPago { get; set; }
        public int IdTipoMoneda { get; set; }
        public decimal Total { get; set; }
        public decimal Pagado { get; set; }
        public Nullable<decimal> Convertido { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual FormaPago FormaPago { get; set; }
        public virtual TipoMoneda TipoMoneda { get; set; }
        public virtual ICollection<LineaArticulo> LineaArticuloes { get; set; }
    }
}
