

//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace slnDatos
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class FacturacionEntidades : DbContext
{
    public FacturacionEntidades()
        : base("name=FacturacionEntidades")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Cliente> Clientes { get; set; }

    public DbSet<Factura> Facturas { get; set; }

    public DbSet<LineaArticulo> LineaArticuloes { get; set; }

    public DbSet<Producto> Productos { get; set; }

    public DbSet<Proveedore> Proveedores { get; set; }

    public DbSet<Role> Roles { get; set; }

    public DbSet<Usuario> Usuarios { get; set; }

}

}

