//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class lineaArticulosImpuesto
    {
        public int Impuesto { get; set; }
        public Nullable<int> Costos { get; set; }
        public Nullable<int> Cantidades { get; set; }
        public Nullable<decimal> Total { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
