
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace slnDatos
{

using System;
    using System.Collections.Generic;
    
public partial class lineaArticulosImpuesto
{

    public int Impuesto { get; set; }

    public Nullable<int> Costos { get; set; }

    public Nullable<int> Cantidades { get; set; }

    public Nullable<decimal> Total { get; set; }

    public System.DateTime Fecha { get; set; }

}

}
