//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Articulos = new HashSet<Articulo>();
        }
    
        public int Id { get; set; }
        public string Producto1 { get; set; }
        public int Costo { get; set; }
        public int Utilidad { get; set; }
        public int Impuesto { get; set; }
        public int Existencia { get; set; }
        public int IdProveedor { get; set; }
    
        public virtual ICollection<Articulo> Articulos { get; set; }
        public virtual Proveedore Proveedore { get; set; }
    }
}
