//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.LineaArticuloes = new HashSet<LineaArticulo>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Costo { get; set; }
        public int Utilidad { get; set; }
        public int Impuesto { get; set; }
        public int Existencia { get; set; }
        public int IdProveedor { get; set; }
        public int IdDepartamento { get; set; }
        public bool Gravado { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual ICollection<LineaArticulo> LineaArticuloes { get; set; }
        public virtual Proveedor Proveedore { get; set; }
    }
}
