
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace slnDatos
{

using System;
    using System.Collections.Generic;
    
public partial class Producto
{

    public Producto()
    {

        this.LineaArticuloes = new HashSet<LineaArticulo>();

    }


    public int Id { get; set; }

    public string Producto1 { get; set; }

    public int Costo { get; set; }

    public int Utilidad { get; set; }

    public int Impuesto { get; set; }

    public int Existencia { get; set; }

    public int IdProveedor { get; set; }



    public virtual ICollection<LineaArticulo> LineaArticuloes { get; set; }

    public virtual Proveedore Proveedore { get; set; }

}

}
